name: Feature TODO
description: Plan a feature or enhancement using the Golden Armor Studios template.
title: "[Feature] "
labels:
  - enhancement
  - Coding
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Provide a concise overview of the feature using the guidance from the API docs or product requirements.
      placeholder: "Build the news list experience leveraging the website API reference."
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Break down the work into checklist items.
      value: |-
        - [ ] 
    validations:
      required: true
  - type: input
    id: points
    attributes:
      label: Story Points
      description: Size the effort (e.g., 1, 3, 5, 8).
      placeholder: 5
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Link API reference sections, design docs, or Discord threads that inform this work.
